name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10"]
    env:
      REFRESH_PERIOD: 900
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install mongoDB
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc |  gpg --dearmor | sudo tee /usr/share/keyrings/mongodb.gpg > /dev/null
        echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
        sudo apt update
        sudo apt install mongodb-org
        sudo systemctl enable mongod
        sudo systemctl start mongod
    - name: Install test dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo python -m pip install flake8 wheel
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build Autisto .whl and install
      run: |
        sudo python setup.py bdist_wheel
        sudo python -m pip install dist/*
    - name: Set up Autisto
      env:
        CREDENTIALS: ${{ secrets.AUTISTO_TEST_CREDENTIALS }}
        EMAIL: ${{ secrets.AUTISTO_TEST_EMAIL }}
      run: |
        echo "$CREDENTIALS" > credentials.json
        sudo autisto <<EOF
        credentials.json
        $EMAIL
        $REFRESH_PERIOD
        EOF
        sleep 10
        sudo cat /tmp/autisto.log 
        sudo systemctl status autisto
        sleep 5
        sudo cat /tmp/autisto.log 
        sudo systemctl status autisto
    - name: Test
      env:
        CLIENT_CREDENTIALS: ${{ secrets.AUTISTO_TEST_CREDENTIALS }}
      run: |
        echo "$CLIENT_CREDENTIALS" > client_credentials.json
        echo "Starting test suite"
        sudo REFRESH_PERIOD=$REFRESH_PERIOD python3 tests/test_autisto.py
